### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by CostGranda** [pianosnake/verify-cognito-token#1]
Hello, I'm working with cognito and implementing a way to protect api endpoints using the AWS Cognito tokens and this project seems to work like a charm because I was doing the same based on the decode-jwt for AWS Lambda. I want to ask for the license for personal use or if I can contribute with something. I see a ISC license in the package json but this is the default on the npm init, maybe you forget to change it :)  
Thank you!

**Comment by pianosnake** [comment]
I've updated the license to MIT. Thanks for pointing that out. Enjoy!
